title: Statamic Memberbox
remote_theme: pmarsceill/just-the-docs
search_enabled: true
color_scheme: main
aux_links:
  "Statamic Memberbox on GitHub":
    - "https://github.com/jacksleight/statamic-memberbox"