title: Statamic Members
remote_theme: pmarsceill/just-the-docs
search_enabled: true
color_scheme: main
aux_links:
  "Statamic Members on GitHub":
    - "https://github.com/jacksleight/statamic-members"